#!/usr/bin/env bash
#Bash script installs nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
find="^\tlocation / {"
replace301="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://nyan.cat;\n\t}\n\n\tlocation / {"
replace404="\terror_page 404 /error404.html;\n\n\tadd_header X-Served-By $HOSTNAME;\n\n\tlocation / {"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "s@$find@$replace301@" /etc/nginx/sites-available/default
sudo sed -i "s@$find@$replace404@" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
